### PR TITLE
feat: fill form with default values for checkout

### PR DESCRIPTION
**Pull request by cstavitsky**
- Automatically fill out form with values per https://github.com/sentry-demos/empower/issues/250
- Easter egg: the address is for SF botanical garden

## Screenshot
Screenshot 2023-08-18 at 12 12 10 PM

### CODE REVIEW

**Comment by realkosty** [comment]
Nice!

> - Most of the changes are autoformatting improvements from a VSCode plugin

https://www.notion.so/sentry/Empower-How-to-Contribute-3190417cf9b14e7c895fb352d5c28bd6?pvs=4#7fe9647576904be69985bc4592d7b898

**Comment by cstavitsky** [comment]
Dang, shoulda RTFM 😁 

Thanks, I'll do that and will ping whenever it's 'clean' and ready for a review

**Comment by realkosty** [comment]
> Dang, shoulda RTFM 😁
> 
> Thanks, I'll do that and will ping whenever it's 'clean' and ready for a review

thanks so much 🙏, this should be a one-off thing so that subsequent PRs will have clean diffs

**Comment by cstavitsky** [comment]
@realkosty ready for review

**Review by realkosty — APPROVED** [review]
Woohoo!

**Pull request merged**
