### PR TITLE
fix tests and use better selectors

### PR DESCRIPTION
**Pull request by ndmanvar**
I tested this and made sure all these tests pass against the new sentry_react_native_release

### CODE REVIEW

**Comment by ndmanvar** [comment]
https://github.com/sentry-demos/sentry_react_native/releases/tag/3.0.0

**Comment by ndmanvar** [comment]
ios tests were not broken, only android

**Comment by ndmanvar** [comment]
(env) [neilmanvar@MacBook-Pro-768 tda]$py.test -s -n 1 mobile_native/android_react_native/
================================================ test session starts =================================================
platform darwin -- Python 3.11.6, pytest-7.4.2, pluggy-1.3.0
rootdir: /Users/neilmanvar/git/empower/tda
plugins: forked-1.4.0, xdist-3.1.0
gw0 [7]
.......
================================================== warnings summary ==================================================
mobile_native/android_react_native/test_nativecrash_react_native_android.py::test_nativecrash_react_native_android
mobile_native/android_react_native/test_uncaughtthrownerror_react_native_android.py::test_uncaughtthrownerror_react_native_android
  /Users/neilmanvar/git/empower/tda/env/lib/python3.11/site-packages/appium/webdriver/extensions/applications.py:155: DeprecationWarning: The "launchApp" API is deprecated and will be removed in future versions. See https://github.com/appium/appium/issues/15807
    warnings.warn(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
===================================== 7 passed, 2 warnings in 323.78s (0:05:23) ======================================

GENERATED errors: https://demo.sentry.io/issues/?query=se%3Aneilmanvar-tda-direct-%2A+%21project%3Aempower-tda&start=2023-12-14T23%3A21%3A29&end=2023-12-14T23%3A26%3A54
OWN errors:       https://demo.sentry.io/issues/?project=5390094&query=se%3Aneilmanvar-tda-direct-%2A&start=2023-12-14T23%3A21%3A29&end=2023-12-14T23%3A26%3A54

**Comment by ndmanvar** [comment]
image

**Review by realkosty — APPROVED** [review]

**Pull request merged**
