### PR TITLE
Fix "Uncompressed Asset perf-issue" bug preventing file being fetched from backend

### PR DESCRIPTION
**Pull request by cstavitsky**
Addresses https://github.com/sentry-demos/empower/issues/276

- When trying to get a large file, `uc_big_file.js`, via http://127.0.0.1:8080/uc_assets/uc_big_file.js, the request 404'd.
- Fixed filepaths and renamed for clarity
- 🚧 WIP: still trying to actually trigger the performance issue, although I think it should be triggering [based on the conditions](https://docs.sentry.io/product/issues/issue-details/performance-issues/uncompressed-asset/#:~:text=Uncompressed%20asset%20issues%20happen%20when,that's%20serving%20the%20asset%20file.)

### CODE REVIEW

**Comment by cstavitsky** [comment]
Progress update:

Now that the filepath is correct and we can retrieve the file, need to confirm whether the Uncompressed Asset performance issue is triggered from the frontend.

**Comment by cstavitsky** [comment]
@ndmanvar couple questions from when you implemented before:

1. Even when fetching the UC big file successfully, it takes 500ms for the request to complete -- do we expect it to be longer or does this sound right?

Screenshot 2023-09-26 at 4 19 05 PM

2. the UC **small** file 404s, and it does not appear to exist in the `uc_assets/` [directory in flask](https://github.com/sentry-demos/empower/tree/master/flask/uc_assets). I'm not clear on what its purpose is -- should we remove the frontend code that tries to fetch the small file since there is no file to fetch? Or does failing to fetch the small file via a 404 actually do something I'm not understanding?

**Comment by cstavitsky** [comment]
Screenshot 2023-09-26 at 4 37 49 PM

✅ The span has to be one of either: resource.link or resource.script spans, which in practice means it's a .css or .js file.
✅ It has to be over 512kb in size, (to filter out smaller files that are less likely to benefit from being compressed).
✅ The span duration has to be over 500ms (to filter out faster transfers or assets served in internal networks).
❓ There has to be another asset span in the transaction that has compressed files. This helps filter out cases where a users' browser isn't sending the Accept-Encoding header.

"asset span in the transaction that has compressed files." --> Not sure where the line between compressed/uncompressed is, so would need to be sure that the small file I provided is actually compressed..!

**Comment by cstavitsky** [comment]
@ndmanvar mentions that there's a hidden requirement which is to have this occur X times in a certain time frame to start triggering. Won't trigger if you manually hit the page once.

Next steps: merge this in and confirm whether TDA will pick this up

**Review by ndmanvar — APPROVED** [review]

**Pull request merged**
