### PR TITLE
WIP [flask] update GAE Python 3.8 -> 3.12 to fix broken deploy after dependencies bump

### PR DESCRIPTION
**Pull request by realkosty**
https://github.com/sentry-demos/empower/pull/399 has broken auto-deploy due to
`ERROR: No matching distribution found for numpy==1.26.0` ([GitHub Action logs
](https://github.com/sentry-demos/empower/actions/runs/7968152424/job/21751962787))

# Testing
https://staging-application-monitoring-react-dot-sales-engineering-sf.appspot.com/products?se=kosty_gae-py312&backend=flask

### CODE REVIEW

**Review by asottile-sentry — APPROVED** [review]

**Comment by realkosty** [comment]
@asottile-sentry this doesn't work yet as it creates another problem. Might need your help troubleshooting.

**Comment by asottile-sentry** [comment]
> @asottile-sentry this doesn't work yet as it creates another problem (see sqlalchemy error in the description). Might need your help troubleshooting.

happy to sit down and troubleshoot!  let me know how I can help

**Comment by realkosty** [comment]
Ok, it's fixed now

**Pull request merged**
