### PR TITLE
Force checkout failure on remaining backends

### PR DESCRIPTION
**Pull request by cstavitsky**
https://github.com/sentry-demos/empower/issues/251

- ⚠️ ⚠️ Ruby on Rails (⚠️ ⚠️ did not test because of stupid ruby dependency stuff I wasted a bunch of time trying to solve, chose to just implement the simple change and hope someone else with the local rails project working can test it)
- Express (tested)
- Spring Boot (tested)

### CODE REVIEW

**Comment by cstavitsky** [comment]
@ndmanvar if you want to test out Rails!

**Comment by ndmanvar** [comment]
works (: good work @cstavitsky .
Let's merge this
image

https://testorg-az.sentry.io/issues/4421674299/?project=4504456042774528&query=&referrer=project-issue-stream

**Review by ndmanvar — APPROVED** [review]

**Comment by ndmanvar** [comment]
@cstavitsky we may need to switch the destination branch to master
image

**Comment by cstavitsky** [comment]
> @cstavitsky we may need to switch the destination branch to master

@ndmanvar correct -- the other branch `format_express_dir` needs to get approved and merged first

**Pull request merged**
