### PR TITLE
fix(build): add react-prod-sourcemaps

### PR DESCRIPTION
**Pull request by JonasBa**
Adds react-prod-sourcemaps plugin that remaps react to include sourcemaps. This should improve both error and profiling stack traces

### CODE REVIEW

**Comment by cstavitsky** [comment]
Related to https://github.com/sentry-demos/empower/issues/261

**Comment by cstavitsky** [comment]
## Screenshots of original behavior on main branch

Files minified:

Screenshot 2023-09-27 at 4 37 01 PM

## Screenshots after deploying to staging and testing out

- [Example profile](https://demo.sentry.io/profiling/profile/staging-frontend-javascript/6399cf61fb394d9cbd2db4f5f7a85932/flamegraph/?colorCoding=by+system+vs+application+frame&fov=6939666944%2C10%2C140702816%2C16&query=&sorting=call+order&spanId=9be5845384b7702d&tid=0&view=top+down) with react-dom sources that appear unminified as desired

Screenshot 2023-09-27 at 4 32 16 PM
Screenshot 2023-09-27 at 4 32 03 PM

**Review by cstavitsky — APPROVED** [review]
Tested, screenshots in comments, looks good to me. 👍

**Comment by realkosty** [comment]
@JonasBa Nice!!!

**Pull request merged**
